def get_consumer_dashboard():
    consumer_response = {
        'Credit Facilities in the name of Applicant: (For Personal Loan / Car Loan / Home Loan)': [
            {
                "FI Name": '',
                "Borrower Name": '',
                "Applicant's Role": '',
                "Nature of Facility": '',
                "Sanctioned Limit": '',
                "Position Date": '',
                "Outstanding": '',
                "Overdue": '',
                "CL Status": '',
                "EMI of Term Loan or % of Credit Card Limit / Outstanding": '',
                "Loan Start Date": '',
                "Loan Expiry Date": '',
            },
            {
                "FI Name": '',
                "Borrower Name": '',
                "Applicant's Role": '',
                "Nature of Facility": '',
                "Sanctioned Limit": '',
                "Position Date": '',
                "Outstanding": '',
                "Overdue": '',
                "CL Status": '',
                "EMI of Term Loan or % of Credit Card Limit / Outstanding": '',
                "Loan Start Date": '',
                "Loan Expiry Date": '',
            },
            {
                "FI Name": '',
                "Borrower Name": '',
                "Applicant's Role": '',
                "Nature of Facility": '',
                "Sanctioned Limit": '',
                "Position Date": '',
                "Outstanding": '',
                "Overdue": '',
                "CL Status": '',
                "EMI of Term Loan or % of Credit Card Limit / Outstanding": '',
                "Loan Start Date": '',
                "Loan Expiry Date": '',
            }
        ],
        'Credit Facilities in the name of Applicant: (For Credit Card)': [
            {
                "FI Name": '',
                "Borrower Name": '',
                "Applicant's Role": '',
                "Nature of Facility": '',
                "Sanctioned Limit": '',
                "Position Date": '',
                "Outstanding": '',
                "Last 12 months Average of Credit Card Outstanding": '',
                "Overdue": '',
                "CL Status": '',
                "EMI of Term Loan or % of Credit Card Limit / Outstanding": '',
                "Loan Start Date": '',
                "Loan Expiry Date": '',
            },
            {
                "FI Name": '',
                "Borrower Name": '',
                "Applicant's Role": '',
                "Nature of Facility": '',
                "Sanctioned Limit": '',
                "Position Date": '',
                "Outstanding": '',
                "Last 12 months Average of Credit Card Outstanding": '',
                "Overdue": '',
                "CL Status": '',
                "EMI of Term Loan or % of Credit Card Limit / Outstanding": '',
                "Loan Start Date": '',
                "Loan Expiry Date": '',
            },
            {
                "FI Name": '',
                "Borrower Name": '',
                "Applicant's Role": '',
                "Nature of Facility": '',
                "Sanctioned Limit": '',
                "Position Date": '',
                "Outstanding": '',
                "Last 12 months Average of Credit Card Outstanding": '',
                "Overdue": '',
                "CL Status": '',
                "EMI of Term Loan or % of Credit Card Limit / Outstanding": '',
                "Loan Start Date": '',
                "Loan Expiry Date": '',
            },
        ],
        "Credit Facilities in the name of Applicant's Business: (For Personal Loan / Car Loan / Home Loan / Credit Card)": [
            {
                "FI Name": '',
                "Borrower Name": '',
                "Applicant's Role": '',
                "Nature of Facility": '',
                "Limit": '',
                "Position Date": '',
                "Outstanding": '',
                "Overdue": '',
                "CL Status": '',
                "Interest Rate of CC-Hypo / OD (%)": '',
                "EMI of Term Loan or Monthly Interest of CC/OD": '',
                "Loan Start Date": '',
                "Loan Expiry Date": '',
            },
            {
                "FI Name": '',
                "Borrower Name": '',
                "Applicant's Role": '',
                "Nature of Facility": '',
                "Limit": '',
                "Position Date": '',
                "Outstanding": '',
                "Overdue": '',
                "CL Status": '',
                "Interest Rate of CC-Hypo / OD (%)": '',
                "EMI of Term Loan or Monthly Interest of CC/OD": '',
                "Loan Start Date": '',
                "Loan Expiry Date": '',
            },
            {
                "FI Name": '',
                "Borrower Name": '',
                "Applicant's Role": '',
                "Nature of Facility": '',
                "Limit": '',
                "Position Date": '',
                "Outstanding": '',
                "Overdue": '',
                "CL Status": '',
                "Interest Rate of CC-Hypo / OD (%)": '',
                "EMI of Term Loan or Monthly Interest of CC/OD": '',
                "Loan Start Date": '',
                "Loan Expiry Date": '',
            },
        ]
    }
    
    return consumer_response