apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-cib-deployments
  namespace: dev-cib-analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cib-analyser
  template:
    metadata:
      labels:
        app: cib-analyser
    spec:
      containers:
        - name: cib-analyser
          # image: dharapat.azurecr.io/dharapat-prime-bank-cib:v1.0.5
          image: __DOCKER_REPOSITORY__/__IMAGE_NAME__:__IMAGE_TAG__
          env:
            - name: PYTHONUNBUFFERED
              value: "1"

      imagePullSecrets:
        - name: cib-registry-key