apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-cib-deployments
  namespace: dev-cib-analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cib-analyser
  template:
    metadata:
      labels:
        app: cib-analyser
    spec:
      containers:
        - name: worker
          image: docker-image
          command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "--timeout", "600", "cib_analytics.wsgi"]
          env:
            - name: PYTHONUNBUFFERED
              value: analyser"1"
        - name: cib-analyser
          image: docker-image
          imagePullPolicy: "Always"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"

      imagePullSecrets:
        - name: cib-registry-key