apiVersion: v1
kind: Service
metadata:
  name: dev-cib-service
  namespace: pbl-cib-analytics
spec:
  selector:
    app: cib-analyser
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer