name: Build & Deploy to Azure
on:
  workflow_dispatch:
  push:
    branches:
      - main
    path:
      .github/workflows/azure.yml
#      - develop

env:
  azure_registry_username: ${{secrets.AZURE_REGISTRY_USERNAME}}
  azure_registry_password: ${{secrets.AZURE_REGISTRY_PASSWORD}}
  azure_registry: ${{secrets.AZURE_REGISTRY}}
  repo_name: ${{secrets.REPO_NAME}}
  azure_credentials: ${{secrets.AZURE_CREDENTIALS}}
  azure_cluster_url: ${{secrets.AZURE_CLUSTER_URL}}
  azure_cluster_token: ${{secrets.AZURE_CLUSTER_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Mode Name
        id: mode
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "mode_name=main" >> $GITHUB_ENV
          elif [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            echo "mode_name=dev" >> $GITHUB_ENV
          fi
      - name: Check Mode Name
        run: echo ${{ env.mode_name }}
      - uses: satackey/action-docker-layer-caching@v0.0.4
      - name: Build & Push Actions
        uses: docker/build-push-action@v1
        with:
          username: ${{env.azure_registry_username}}
          password: ${{env.azure_registry_password}}
          registry: ${{env.azure_registry}}
          repository: ${{github.workspace}}/DockerFile
          tag_with_sha: true
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Mode Name
        id: mode
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "mode_name=main" >> $GITHUB_ENV
          elif [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            echo "mode_name=dev" >> $GITHUB_ENV
          fi
      - name: Check Mode Name
        run: echo ${{ env.mode_name }}
      - name: Set Repo Location # steps required to find the image id of our image from container registry
        id: repo
        run: echo "::set-output name=repo_name::${{ env.azure_registry }}/${{env.mode_name}}-${{env.repo_name}}:sha-$(git rev-parse --short HEAD)" # we are setting the image location as output to be used in later step
      - name: Check Repo Location
        run: echo ${{ steps.repo.outputs.repo_name }} # checking our repo location
      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.azure_credentials }}
      - uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{env.azure_cluster_url}}
          k8s-secret: ${{env.azure_cluster_token}}
        id: setcontext
      - name: Install Helm # helm installation in our runner for deploying.
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm version
      - name: Delete jobs
        run: |
          kubectl delete jobs --all
      - name: Install chart
        run: >
          helm upgrade
          --install
          --set images.bankstatement="${{ steps.repo.outputs.repo_name }}"
          --set mode_name="${{env.mode_name}}"
          --wait
          --atomic
          ${{env.mode_name}}-bankstatement-k8-charts
          ./k8s
#      - name: Install istio charts
#        run: >
#          helm upgrade
#          --install
#          --set mode_name="${{env.mode_name}}"
#          --set sub_domain="${{env.sub_domain}}"
#          --wait
#          --atomic
#          ${{env.mode_name}}-management-istio-charts
#          ./istio-charts
      - name: Check pods # checking pod list to see if they are running.
        run: |
          kubectl get pods --namespace=${{env.mode_name}}-bankstatement
          kubectl get svc --namespace=${{env.mode_name}}-bankstatement